spring:
  datasource:
    # 운영 환경용 log4jdbc 설정 적용
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mysql://${DB_IP}:3306/swim_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: none

  flyway:
    enabled: true
    baseline-on-migrate: false # 기존 DB가 비어있을 때 마이그레이션을 정상 가동합니다.

server:
  port: ${PORT} # 도커 컴포즈 (.env)에서 지정해 줄 포트 번호를 따라갑니다.