spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/swim_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: swim_user
    password: qwer1234!
  sql:
    init:
      mode: always # 앱이 켜질 대마다 schema.sql, data.sql을 실행
  jpa:
    hibernate:
      ddl-auto: none

server:
  port: 8092
