services:
  toeic-mariadb:
    image: mariadb:11.4
    container_name: toeic-mariadb
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: root1234
      MARIADB_DATABASE: toeic_db
      MARIADB_USER: kyg
      MARIADB_PASSWORD: kyg1234
    ports:
      - "3307:3306"
    volumes:
      - toeic_mariadb_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  toeic_mariadb_data:
