CREATE TABLE IF NOT EXISTS word_tbl (
    id INT PRIMARY KEY AUTO_INCREMENT COMMENT '단어 고유 번호',
    vocabulary VARCHAR(100) NOT NULL COMMENT '영단어',
    meaning VARCHAR(255) NOT NULL COMMENT '뜻',
    example_sentence VARCHAR(500) NOT NULL COMMENT '예문',
    is_memorized BOOLEAN NOT NULL DEFAULT FALSE COMMENT '암기 여부',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성일시'
);
